
spring:
  application:
    name: boms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          ####开启Service_id 用时需要大写service_id
          enabled: true
          lowerCaseServiceId: true