feign:
  compression:
    request:
      enabled: true
      mime-types: ["text/xml","application/xml","application/json"]
      min-request-size: 2048
    response.enabled: true



hystrix.command.default.execution:
  timeout.enabled: true
  isolation:
    thread:
      timeoutInMilliseconds: 60000
