spring:

  redis:
    database: 1
    host: 47.100.3.157
    password:
    timeout: 3000
    jedis:
      pool:
        max-active: 5
        min-idle: 0
        max-wait: 1
        max-idle: 8
    port: 6061

    redisson:
      config: classpath:redisson.yaml