server:
  port: 8001

spring:
  application:
    name: ins-config
  cloud:
    config:
      server:
        svn:
          uri: svn://svn.hailijr.com:9099/tec/config/
          username: kehengcheng
          password: hlkhc1q2w
          default-label: trunk
          search-paths:
            - ins-order
  profiles:
    active: subversion


register.center: http://127.0.0.1:9999/eureka/
eureka:
  client:
    # 开启健康检查
    healthcheck.enabled: true
    # feign 间隔多久去拉取服务注册信息(默认 30 秒)
    registry-fetch-interval-seconds: 10
    serviceUrl.defaultZone: ${register.center}
  instance:
    # feign 发送心跳给 server 端的频率(默认 30 秒)
    lease-renewal-interval-in-seconds: 5
    # server 收到心跳等待下一次心跳的超时时间, 要比上面的大(默认 90 秒)
    lease-expiration-duration-in-seconds: 10
    preferIpAddress: true
    instance-id: ${spring.cloud.feign.ipAddress}:${server.port}