logging.config: classpath:log4j2.xml
## org.springframework.boot.autoconfigure.web.ServerProperties
server:
  port: 9101
  servlet:
    session:
      cookie:
        name: OAUTH2SESSION # This is to prevent cookie clash with other service as they run on the same host and context path

management:
  endpoint:
    health:
      show-details: always


##  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  application:
    name: api-gateway
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  main.allow-bean-definition-overriding: true
  haili:
    web:
      swagger2:
        enabled: true
      filter:
        enabled: true
#   cat:
#     zuul.enabled: true




register.center: http://127.0.0.1:9997/eureka #,http://eureka2:9998/eureka,http://eureka3:9999/eureka

eureka:
  client:
    # 开启健康检查
    healthcheck.enabled: false
    # feign 间隔多久去拉取服务注册信息(默认 30 秒)
    registry-fetch-interval-seconds: 10
    service-url.defaultZone: ${register.center}
  instance:
    # feign 发送心跳给 server 端的频率(默认 30 秒)
    lease-renewal-interval-in-seconds: 5
    # server 收到心跳等待下一次心跳的超时时间, 要比上面的大(默认 90 秒)
    lease-expiration-duration-in-seconds: 10
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}



feign:
  compression:
    request:
      enabled: true
      mime-types: ["text/xml","application/xml","application/json"]
      min-request-size: 2048
    response.enabled: true
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true
  ## 配置httpclient线程池
  httpclient:
    enabled: false
  okhttp:
    enabled: true
    log.level: "HEADERS"

hystrix.command.default.execution:
  timeout.enabled: true
  isolation:
    thread:
      timeoutInMilliseconds: 60000

ribbon:
  http:
    client:
      enabled: false
  okhttp:
    enabled: true

# 路由
zuul:
  ribbon:
    eager-load:
      enabled: true
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    max-per-route-connections: 20
    max-total-connections: 200
    connection-request-timeout-millis: 500
  routes:
    auth:
      path: /auth/**
      service-id: oauth2-jwt-server
      sensitive-headers:
      custom-sensitive-headers: true
    member:
      path: /member/**
      service-id: member-server
      sensitive-headers:
      custom-sensitive-headers: true
  retryable: true



auth:
  permitall:
    -
      pattern: /auth/oauth/**
    -
      pattern: /auth/auth/user
    -
      pattern: /**/public/**
    -
      pattern: /actuator/**

security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
      client-id: frontend
      client-secret: frontend
    resource:
      prefer-token-info: false
      user-info-uri: http://localhost:8999/auth/user
      load-balanced: true
#      token-info-uri: http://localhost:${server.port}/auth/oauth/check_token
#      token-type: Bearer
#      jwt:
#        key-value: secret #使用对称加密方式，默认算法为HS256
