
## org.springframework.boot.autoconfigure.web.ServerProperties
server:
  port: 9101
#  servlet:
#    session:
#      cookie:
#        name: OAUTH2SESSION # This is to prevent cookie clash with other service as they run on the same host and context path

management:
  endpoint:
    health:
      show-details: always


##  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  application:
    name: api-gateway
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true


# 路由
zuul:
  ribbon:
    eager-load:
      enabled: true
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    max-per-route-connections: 20
    max-total-connections: 200
    connection-request-timeout-millis: 500
  routes:
    auth:
      path: /auth/**
      service-id: oauth2-jwt-server
      sensitive-headers:
      custom-sensitive-headers: true
    member:
      path: /member/**
      service-id: member-server
      sensitive-headers:
      custom-sensitive-headers: true
    order:
      path: /order/**
      service-id: order-server
      sensitive-headers:
      custom-sensitive-headers: true
  retryable: true



auth:
  permitall:
    -
      pattern: /auth/**
    -
      pattern: /**/public/**
    -
      pattern: /actuator/**

security:
  oauth2:
    client:
      access-token-uri: http://localhost:${server.port}/auth/oauth/token
      user-authorization-uri: http://localhost:${server.port}/auth/oauth/authorize
      client-id: frontend
      client-secret: frontend
    resource:
      prefer-token-info: false
      user-info-uri: http://localhost:8999/auth/user
      load-balanced: true
#      token-info-uri: http://localhost:${server.port}/auth/oauth/check_token
#      token-type: Bearer
#      jwt:
#        key-value: secret #使用对称加密方式，默认算法为HS256
