spring:
  # 当前服务名
  application.name: account-service

  datasource:
    url: jdbc:mysql://47.100.3.157:3306/account?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    userName: root
    password: 123456

  ####Redis配置 # org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  redis:
    database: 2
    host: 47.100.3.157
    password:
    timeout: 3000
    jedis:
      pool:
        max-active: 5
        min-idle: 0
        max-wait: 1
        max-idle: 8
    port: 6061
    redisson:
      config: classpath:redisson.yaml

  rabbitmq:
    #配置rabbitmq的主机
    host: 47.100.3.157
    #访问端口
    port: 5672
    #安装RabbitMQ时配置的用户名
    username: root
    #安装RabbitMQ时配置的密码
    password: 123456
    #消息发送到交换机确认机制,是否确认回调
    publisher-confirms: true
    #消息发送到交换机确认机制,是否返回回调
    publisher-returns: true
    listener:
      simple:
        #采用手动应答
        acknowledge-mode: manual
        #指定最小消费者数量
        concurrency: 1
        #指定最大消费者数量
        max-concurrency: 1
        retry:
          #是否支持重试
          enabled: true
      direct:
        acknowledge-mode: manual
    connection-timeout: 50000

mq:
  retry:
    count: 5
  message:
    exchange:
      name: "account-exchange"
      queue:
        name: "account-queue"
      routing-key:
        name: "account-routing-key"
    dead:
      exchange:
        name: "account-dead-exchange"
        queue:
          name: "account-dead-queue"
        routing-key:
          name: "account-dead-routing-key"