logging.config: classpath:log4j2.xml
online: false

## org.springframework.boot.autoconfigure.web.ServerProperties
server.port: 8999

spring:
  # 当前服务名
  application.name: oauth2-jwt-server
#####haili自定义的配置
  haili:
    web:
      swagger2:
        enabled: true
      filter:
        enabled: true
####cat链追踪配置
#    cat:
#      web.enabled: true
#      feign.enabled: true
#      mybatis.enabled: true
######haili自定义的配置

  # 配置下面两个值将会走到 ControllerAdvice 全局里面去
  # org.springframework.boot.autoconfigure.web.WebMvcProperties
  mvc.throw-exception-if-no-handler-found: true
  # org.springframework.boot.autoconfigure.web.ResourceProperties
  resources.add-mappings: false
#####数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    userName: root
    password: 111111
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
####Redis配置 # org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  redis:
    database: 0
    host: 47.100.3.157
    password:
    timeout: 3000
    jedis:
      pool:
        max-active: 5
        min-idle: 0
        max-wait: 1
        max-idle: 8
    port: 6061
    redisson:
      config: classpath:redisson.yaml
######分页配置
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

###mybatis配置
mybatis:
  type-aliases-package: com.haili.ins.dao.model
  mapper-locations: classpath*:/mybatis/*.xml

##tk.mybatis配置
mapper:
  #mappers: tk.mybatis.mapper.common.Mapper,tk.mybatis.mapper.common.Mapper2
  notEmpty: true

# 注册中心地址, 多个使用 , 分隔
register.center: http://127.0.0.1:9997/eureka

eureka:
  client:
    # 开启健康检查
    healthcheck.enabled: true
    # client 间隔多久去拉取服务注册信息(默认 30 秒)
    registry-fetch-interval-seconds: 10
    serviceUrl.defaultZone: ${register.center}
  instance:
    # client 发送心跳给 server 端的频率(默认 30 秒)
    lease-renewal-interval-in-seconds: 5
    # server 收到心跳等待下一次心跳的超时时间, 要比上面的大(默认 90 秒)
    lease-expiration-duration-in-seconds: 10
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

feign:
  compression:
    request:
      enabled: true
      mime-types: ["text/xml","application/xml","application/json"]
      min-request-size: 2048
    response.enabled: true
  hystrix:
    # 在feign中开启hystrix功能，默认情况下feign不开启hystrix功能
    enabled: true
  ## 配置httpclient线程池
  httpclient:
    enabled: false
  okhttp:
    enabled: true
    log.level: "HEADERS"

hystrix.command.default.execution:
  timeout.enabled: true
  isolation:
    thread:
      timeoutInMilliseconds: 60000


#apollo:
#  bootstrap:
#    enabled: true
#    namespaces: application,log4j2
#  #    eagerLoad:
#  #      enabled=true:
#  meta: http://172.19.250.6:8080
#  cacheDir: /opt/apollo/data/member-facade