
spring:
  # 当前服务名
  application.name: oauth2-jwt-server

  datasource:
    url: jdbc:mysql://47.100.3.157:3306/oauth?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    userName: root
    password: 123456
####Redis配置 # org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  redis:
    database: 0
    host: 47.100.3.157
    password:
    timeout: 3000
    jedis:
      pool:
        max-active: 5
        min-idle: 0
        max-wait: 1
        max-idle: 8
    port: 6061
    redisson:
      config: classpath:redisson.yaml