## org.springframework.boot.autoconfigure.web.ServerProperties
server.port: 8999
spring:
  # 当前服务名
  application.name: txncore-service

  datasource:
    url: jdbc:mysql://47.100.3.157:3306/txncore?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    userName: root
    password: 123456




